language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - USER=testUser

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y dh-make

install: "pip install -r requirements.txt"

script: py.test

